package repository

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"realtime-chat-system/internal/models"
	"realtime-chat-system/pkg/errors"
	"realtime-chat-system/pkg/logAction"
	"realtime-chat-system/pkg/logger"
	"realtime-chat-system/pkg/mlog"
)

// MessageRepository defines the interface for message data access
type MessageRepository interface {
	Create(ctx context.Context, message *models.Message) error
	FindByID(ctx context.Context, id string) (*models.Message, error)
	FindByRoom(ctx context.Context, roomID string, limit, offset int) ([]*models.Message, error)
	FindByRoomProjection(ctx context.Context, roomID string, projection []string, limit, offset int) ([]*models.Message, error)
	Update(ctx context.Context, message *models.Message) error
	Delete(ctx context.Context, messageID string) error
}

// messageRepository implements MessageRepository
type messageRepository struct {
	collection *mongo.Collection
}

// NewMessageRepository creates a new message repository
func NewMessageRepository(db *mongo.Database) MessageRepository {
	return &messageRepository{
		collection: db.Collection("messages"),
	}
}

// Create creates a new message
func (r *messageRepository) Create(ctx context.Context, message *models.Message) error {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	// Generate new ObjectID if not provided
	if message.ID == "" {
		message.ID = primitive.NewObjectID().Hex()
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_CREATE, "mongo insert message"), map[string]any{
		"document": message,
	})

	result, err := r.collection.InsertOne(ctx, message)
	end := time.Since(start).Milliseconds()

	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_CREATE, "mongo insert message"), map[string]any{
			"error": err.Error(),
		})
		return errors.ErrDatabase(err)
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_CREATE, "mongo insert message"), map[string]any{
		"result": result,
	})

	// Update message ID with inserted ID if it was generated by MongoDB
	if oid, ok := result.InsertedID.(primitive.ObjectID); ok {
		message.ID = oid.Hex()
	}

	return nil
}

// FindByID finds a message by ID
func (r *messageRepository) FindByID(ctx context.Context, id string) (*models.Message, error) {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	var message models.Message

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(id); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": id}
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "mongo find message by id"), map[string]any{
		"filter": filter,
	})

	err := r.collection.FindOne(ctx, filter).Decode(&message)
	end := time.Since(start).Milliseconds()

	result := map[string]any{}
	if err != nil {
		result["status"] = "error"
		result["error"] = err.Error()
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find message by id"), result)
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrMessageNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}
	result["status"] = "success"
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find message by id"), result)

	return &message, nil
}

// FindByRoom finds messages in a room with pagination
// Messages are returned in reverse chronological order (newest first)
func (r *messageRepository) FindByRoom(ctx context.Context, roomID string, limit, offset int) ([]*models.Message, error) {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	filter := bson.M{"roomId": roomID}

	// Set default limit if not provided
	if limit <= 0 {
		limit = 50
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "mongo find messages by room"), map[string]any{
		"filter": filter,
		"limit":  limit,
		"offset": offset,
	})

	// Create options for pagination and sorting
	opts := options.Find().
		SetLimit(int64(limit)).
		SetSkip(int64(offset)).
		SetSort(bson.D{{Key: "createdAt", Value: -1}}) // Sort by createdAt descending (newest first)

	cursor, err := r.collection.Find(ctx, filter, opts)
	end := time.Since(start).Milliseconds()

	result := map[string]any{}

	if err != nil {
		result["status"] = "error"
		result["error"] = err.Error()
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find messages by room"), result)
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var messages []*models.Message
	if err := cursor.All(ctx, &messages); err != nil {
		return nil, errors.ErrDatabase(err)
	}
	result["status"] = "success"
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find messages by room"), result)

	return messages, nil
}

// FindByRoomProjection finds messages in a room with projection (only load specified fields)
// This is more efficient when you don't need all fields (e.g., skip status)
func (r *messageRepository) FindByRoomProjection(ctx context.Context, roomID string, projection []string, limit, offset int) ([]*models.Message, error) {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	filter := bson.M{"roomId": roomID}

	// Set default limit if not provided
	if limit <= 0 {
		limit = 50
	}

	// Create projection bson
	projectionBson := bson.M{}
	for _, field := range projection {
		projectionBson[field] = 1
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "mongo find messages by room with projection"), map[string]any{
		"filter":     filter,
		"projection": projectionBson,
		"limit":      limit,
		"offset":     offset,
	})
	// Create options for pagination, sorting, and projection
	opts := options.Find().
		SetLimit(int64(limit)).
		SetSkip(int64(offset)).
		SetSort(bson.D{{Key: "createdAt", Value: -1}}). // Sort by createdAt descending (newest first)
		SetProjection(projectionBson)

	cursor, err := r.collection.Find(ctx, filter, opts)
	end := time.Since(start).Milliseconds()

	result := map[string]any{}

	if err != nil {
		result["status"] = "error"
		result["error"] = err.Error()
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find messages by room with projection"), result)
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var messages []*models.Message
	if err := cursor.All(ctx, &messages); err != nil {
		return nil, errors.ErrDatabase(err)
	}
	result["status"] = "success"
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "mongo find messages by room with projection"), result)

	return messages, nil
}

// Update updates a message
func (r *messageRepository) Update(ctx context.Context, message *models.Message) error {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(message.ID); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": message.ID}
	}

	update := bson.M{
		"$set": bson.M{
			"content":   message.Content,
			"updatedAt": message.UpdatedAt,
			"editedAt":  message.EditedAt,
			"deleted":   message.Deleted,
			"status":    message.Status,
		},
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_UPDATE, "mongo update message"), map[string]any{
		"filter": filter,
		"update": update,
	})

	result, err := r.collection.UpdateOne(ctx, filter, update)
	end := time.Since(start).Milliseconds()

	resultLog := map[string]any{}
	if err != nil {
		resultLog["status"] = "error"
		resultLog["error"] = err.Error()
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "mongo update message"), resultLog)
		return errors.ErrDatabase(err)
	}
	resultLog["status"] = "success"
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "mongo update message"), resultLog)

	if result.MatchedCount == 0 {
		return errors.ErrMessageNotFound()
	}

	return nil
}

// Delete marks a message as deleted (soft delete)
func (r *messageRepository) Delete(ctx context.Context, messageID string) error {
	dependency := "mongo"
	log := mlog.L(ctx)
	start := time.Now()

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(messageID); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": messageID}
	}

	update := bson.M{
		"$set": bson.M{
			"deleted": true,
		},
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: dependency,
	}).Debug(logAction.DB_REQUEST(logAction.DB_UPDATE, "mongo delete message"), map[string]any{
		"filter": filter,
		"update": update,
	})

	result, err := r.collection.UpdateOne(ctx, filter, update)
	end := time.Since(start).Milliseconds()

	resultLog := map[string]any{}
	if err != nil {
		resultLog["status"] = "error"
		resultLog["error"] = err.Error()
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   dependency,
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "mongo delete message"), resultLog)
		return errors.ErrDatabase(err)
	}
	resultLog["status"] = "success"
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   dependency,
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "mongo delete message"), resultLog)

	if result.MatchedCount == 0 {
		return errors.ErrMessageNotFound()
	}

	return nil
}
