package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"realtime-chat-system/internal/models"
	"realtime-chat-system/pkg/errors"
)

// MessageRepository defines the interface for message data access
type MessageRepository interface {
	Create(ctx context.Context, message *models.Message) error
	FindByID(ctx context.Context, id string) (*models.Message, error)
	FindByRoom(ctx context.Context, roomID string, limit, offset int) ([]*models.Message, error)
	FindByRoomProjection(ctx context.Context, roomID string, projection []string, limit, offset int) ([]*models.Message, error)
	Update(ctx context.Context, message *models.Message) error
	Delete(ctx context.Context, messageID string) error
}

// messageRepository implements MessageRepository
type messageRepository struct {
	collection *mongo.Collection
}

// NewMessageRepository creates a new message repository
func NewMessageRepository(db *mongo.Database) MessageRepository {
	return &messageRepository{
		collection: db.Collection("messages"),
	}
}

// Create creates a new message
func (r *messageRepository) Create(ctx context.Context, message *models.Message) error {
	// Generate new ObjectID if not provided
	if message.ID == "" {
		message.ID = primitive.NewObjectID().Hex()
	}

	result, err := r.collection.InsertOne(ctx, message)
	if err != nil {
		return errors.ErrDatabase(err)
	}

	// Update message ID with inserted ID if it was generated by MongoDB
	if oid, ok := result.InsertedID.(primitive.ObjectID); ok {
		message.ID = oid.Hex()
	}

	return nil
}

// FindByID finds a message by ID
func (r *messageRepository) FindByID(ctx context.Context, id string) (*models.Message, error) {
	var message models.Message

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(id); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": id}
	}

	err := r.collection.FindOne(ctx, filter).Decode(&message)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrMessageNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	return &message, nil
}

// FindByRoom finds messages in a room with pagination
// Messages are returned in reverse chronological order (newest first)
func (r *messageRepository) FindByRoom(ctx context.Context, roomID string, limit, offset int) ([]*models.Message, error) {
	filter := bson.M{"roomId": roomID}

	// Set default limit if not provided
	if limit <= 0 {
		limit = 50
	}

	// Create options for pagination and sorting
	opts := options.Find().
		SetLimit(int64(limit)).
		SetSkip(int64(offset)).
		SetSort(bson.D{{Key: "createdAt", Value: -1}}) // Sort by createdAt descending (newest first)

	cursor, err := r.collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var messages []*models.Message
	if err := cursor.All(ctx, &messages); err != nil {
		return nil, errors.ErrDatabase(err)
	}

	return messages, nil
}

// FindByRoomProjection finds messages in a room with projection (only load specified fields)
// This is more efficient when you don't need all fields (e.g., skip status)
func (r *messageRepository) FindByRoomProjection(ctx context.Context, roomID string, projection []string, limit, offset int) ([]*models.Message, error) {
	filter := bson.M{"roomId": roomID}

	// Set default limit if not provided
	if limit <= 0 {
		limit = 50
	}

	// Create projection bson
	projectionBson := bson.M{}
	for _, field := range projection {
		projectionBson[field] = 1
	}

	// Create options for pagination, sorting, and projection
	opts := options.Find().
		SetLimit(int64(limit)).
		SetSkip(int64(offset)).
		SetSort(bson.D{{Key: "createdAt", Value: -1}}). // Sort by createdAt descending (newest first)
		SetProjection(projectionBson)

	cursor, err := r.collection.Find(ctx, filter, opts)
	if err != nil {
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var messages []*models.Message
	if err := cursor.All(ctx, &messages); err != nil {
		return nil, errors.ErrDatabase(err)
	}

	return messages, nil
}

// Update updates a message
func (r *messageRepository) Update(ctx context.Context, message *models.Message) error {
	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(message.ID); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": message.ID}
	}

	update := bson.M{
		"$set": bson.M{
			"content":   message.Content,
			"updatedAt": message.UpdatedAt,
			"editedAt":  message.EditedAt,
			"deleted":   message.Deleted,
			"status":    message.Status,
		},
	}

	result, err := r.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.ErrDatabase(err)
	}

	if result.MatchedCount == 0 {
		return errors.ErrMessageNotFound()
	}

	return nil
}

// Delete marks a message as deleted (soft delete)
func (r *messageRepository) Delete(ctx context.Context, messageID string) error {
	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(messageID); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": messageID}
	}

	update := bson.M{
		"$set": bson.M{
			"deleted": true,
		},
	}

	result, err := r.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.ErrDatabase(err)
	}

	if result.MatchedCount == 0 {
		return errors.ErrMessageNotFound()
	}

	return nil
}
