package repository

import (
	"context"
	"sort"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"

	"realtime-chat-system/internal/models"
	"realtime-chat-system/pkg/errors"
	"realtime-chat-system/pkg/logAction"
	"realtime-chat-system/pkg/logger"
	"realtime-chat-system/pkg/mlog"
)

// RoomRepository defines the interface for room data access
type RoomRepository interface {
	Create(ctx context.Context, room *models.Room) error
	FindByID(ctx context.Context, id string) (*models.Room, error)
	FindByMembers(ctx context.Context, memberIDs []string) (*models.Room, error)
	FindUserRooms(ctx context.Context, userID string) ([]*models.Room, error)
	UpdateMembers(ctx context.Context, roomID string, members []string) error
}

// roomRepository implements RoomRepository
type roomRepository struct {
	collection *mongo.Collection
}

// NewRoomRepository creates a new room repository
func NewRoomRepository(db *mongo.Database) RoomRepository {
	return &roomRepository{
		collection: db.Collection("rooms"),
	}
}

// Create creates a new room
func (r *roomRepository) Create(ctx context.Context, room *models.Room) error {
	log := mlog.L(ctx)
	startTime := time.Now()
	// Generate new ObjectID if not provided
	if room.ID == "" {
		room.ID = primitive.NewObjectID().Hex()
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_CREATE, "Create room"), room)
	//

	result, err := r.collection.InsertOne(ctx, room)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_CREATE, "Create room"), map[string]any{
			"error": err.Error(),
		})
		return errors.ErrDatabase(err)
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_CREATE, "Create room"), map[string]any{
		"result": room,
	})

	// Update room ID with inserted ID if it was generated by MongoDB
	if oid, ok := result.InsertedID.(primitive.ObjectID); ok {
		room.ID = oid.Hex()
	}

	return nil
}

// FindByID finds a room by ID
func (r *roomRepository) FindByID(ctx context.Context, id string) (*models.Room, error) {
	log := mlog.L(ctx)
	startTime := time.Now()

	var room models.Room

	// First try to find by string ID
	filter := bson.M{"_id": id}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find room by ID"), filter)
	//
	err := r.collection.FindOne(ctx, filter).Decode(&room)
	end := time.Since(startTime).Microseconds()
	if err == nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find room by ID"), map[string]any{
			"result": room,
		})
		return &room, nil
	}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find room by ID"), map[string]any{
		"error": err.Error(),
	})

	// If not found and ID is valid ObjectID hex, try as ObjectID
	if err == mongo.ErrNoDocuments {
		if oid, parseErr := primitive.ObjectIDFromHex(id); parseErr == nil {
			filter = bson.M{"_id": oid}
			err = r.collection.FindOne(ctx, filter).Decode(&room)
			if err == nil {
				return &room, nil
			}
		}
	}

	if err == mongo.ErrNoDocuments {
		return nil, errors.ErrRoomNotFound()
	}
	return nil, errors.ErrDatabase(err)
}

// FindByMembers finds a direct room by its members
// For direct rooms, we need to find a room with exactly these 2 members
func (r *roomRepository) FindByMembers(ctx context.Context, memberIDs []string) (*models.Room, error) {
	log := mlog.L(ctx)
	startTime := time.Now()

	if len(memberIDs) != 2 {
		return nil, errors.ErrInvalidInput("FindByMembers requires exactly 2 member IDs for direct rooms")
	}

	// Sort member IDs to ensure consistent ordering
	sortedMembers := make([]string, len(memberIDs))
	copy(sortedMembers, memberIDs)
	sort.Strings(sortedMembers)

	// Find direct room with these exact members
	filter := bson.M{
		"type":    models.RoomTypeDirect,
		"members": bson.M{"$all": sortedMembers, "$size": 2},
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find direct room by members"), filter)
	//

	var room models.Room
	err := r.collection.FindOne(ctx, filter).Decode(&room)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find direct room by members"), map[string]any{
			"error": err.Error(),
		})
		if err == mongo.ErrNoDocuments {
			return nil, nil // Return nil without error if not found
		}
		return nil, errors.ErrDatabase(err)
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find direct room by members"), map[string]any{
		"result": room,
	})

	return &room, nil
}

// FindUserRooms finds all rooms that a user is a member of
func (r *roomRepository) FindUserRooms(ctx context.Context, userID string) ([]*models.Room, error) {
	log := mlog.L(ctx)
	startTime := time.Now()

	filter := bson.M{"members": userID}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find user rooms"), filter)
	//

	cursor, err := r.collection.Find(ctx, filter)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user rooms"), map[string]any{
			"error": err.Error(),
		})
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var rooms []*models.Room
	if err := cursor.All(ctx, &rooms); err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user rooms"), map[string]any{
			"error": err.Error(),
		})
		return nil, errors.ErrDatabase(err)
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user rooms"), map[string]any{
		"result_count": len(rooms),
	})
	return rooms, nil
}

// UpdateMembers updates the members list of a room
func (r *roomRepository) UpdateMembers(ctx context.Context, roomID string, members []string) error {
	log := mlog.L(ctx)
	startTime := time.Now()
	// First try string ID
	filter := bson.M{"_id": roomID}
	update := bson.M{
		"$set": bson.M{
			"members": members,
		},
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_UPDATE, "Update room members"), map[string]any{
		"filter": filter,
		"update": update,
	})
	//

	result, err := r.collection.UpdateOne(ctx, filter, update)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "Update room members"), map[string]any{
			"error": err.Error(),
		})
		return errors.ErrDatabase(err)
	}

	// If not matched and ID is valid ObjectID hex, try as ObjectID
	if result.MatchedCount == 0 {
		if oid, parseErr := primitive.ObjectIDFromHex(roomID); parseErr == nil {
			filter = bson.M{"_id": oid}
			result, err = r.collection.UpdateOne(ctx, filter, update)
			if err != nil {
				log.SetDependencyMetadata(logger.DependencyMetadata{
					Dependency:   r.collection.Name(),
					ResponseTime: end,
				}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "Update room members"), map[string]any{
					"error": err.Error(),
				})
				return errors.ErrDatabase(err)
			}
		}
	}

	if result.MatchedCount == 0 {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "Update room members"), map[string]any{
			"error": "room not found",
		})

		return errors.ErrRoomNotFound()
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_UPDATE, "Update room members"), map[string]any{
		"result": result,
	})
	return nil
}
