package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"

	"realtime-chat-system/internal/models"
	"realtime-chat-system/pkg/errors"
)

// UserRepository defines the interface for user data access
type UserRepository interface {
	Create(ctx context.Context, user *models.User) error
	FindByID(ctx context.Context, id string) (*models.User, error)
	FindByUsername(ctx context.Context, username string) (*models.User, error)
	FindByEmail(ctx context.Context, email string) (*models.User, error)
}

// userRepository implements UserRepository
type userRepository struct {
	collection *mongo.Collection
}

// NewUserRepository creates a new user repository
func NewUserRepository(db *mongo.Database) UserRepository {
	return &userRepository{
		collection: db.Collection("users"),
	}
}

// Create creates a new user
func (r *userRepository) Create(ctx context.Context, user *models.User) error {
	// Generate new ObjectID if not provided
	if user.ID == "" {
		user.ID = primitive.NewObjectID().Hex()
	}

	result, err := r.collection.InsertOne(ctx, user)
	if err != nil {
		// Check for duplicate key error
		if mongo.IsDuplicateKeyError(err) {
			// Determine which field is duplicate
			if containsField(err.Error(), "username") {
				return errors.ErrDuplicateUsername()
			}
			if containsField(err.Error(), "email") {
				return errors.ErrDuplicateEmail()
			}
			return errors.ErrInvalidInput("Duplicate user data")
		}
		return errors.ErrDatabase(err)
	}

	// Update user ID with inserted ID if it was generated by MongoDB
	if oid, ok := result.InsertedID.(primitive.ObjectID); ok {
		user.ID = oid.Hex()
	}

	return nil
}

// FindByID finds a user by ID
func (r *userRepository) FindByID(ctx context.Context, id string) (*models.User, error) {
	var user models.User

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(id); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": id}
	}

	err := r.collection.FindOne(ctx, filter).Decode(&user)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	return &user, nil
}

// FindByUsername finds a user by username
func (r *userRepository) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	var user models.User

	filter := bson.M{"username": username}
	err := r.collection.FindOne(ctx, filter).Decode(&user)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	return &user, nil
}

// FindByEmail finds a user by email
func (r *userRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	var user models.User

	filter := bson.M{"email": email}
	err := r.collection.FindOne(ctx, filter).Decode(&user)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	return &user, nil
}

// containsField checks if error message contains a field name
func containsField(errMsg, field string) bool {
	// Simple check if field name appears in error message
	for i := 0; i < len(errMsg)-len(field)+1; i++ {
		if errMsg[i:i+len(field)] == field {
			return true
		}
	}
	return false
}
