package repository

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"

	"realtime-chat-system/internal/models"
	"realtime-chat-system/pkg/errors"
	"realtime-chat-system/pkg/logAction"
	"realtime-chat-system/pkg/logger"
	"realtime-chat-system/pkg/mlog"
)

// UserRepository defines the interface for user data access
type UserRepository interface {
	Create(ctx context.Context, user *models.User) error
	FindByID(ctx context.Context, id string) (*models.User, error)
	FindByUsername(ctx context.Context, username string) (*models.User, error)
	FindByEmail(ctx context.Context, email string) (*models.User, error)
	SearchByUsername(ctx context.Context, query string, limit int) ([]*models.User, error)
}

// userRepository implements UserRepository
type userRepository struct {
	collection *mongo.Collection
}

// NewUserRepository creates a new user repository
func NewUserRepository(db *mongo.Database) UserRepository {
	return &userRepository{
		collection: db.Collection("users"),
	}
}

// Create creates a new user
func (r *userRepository) Create(ctx context.Context, user *models.User) error {
	// Generate new ObjectID if not provided
	if user.ID == "" {
		user.ID = primitive.NewObjectID().Hex()
	}

	result, err := r.collection.InsertOne(ctx, user)
	if err != nil {
		// Check for duplicate key error
		if mongo.IsDuplicateKeyError(err) {
			// Determine which field is duplicate
			if containsField(err.Error(), "username") {
				return errors.ErrDuplicateUsername()
			}
			if containsField(err.Error(), "email") {
				return errors.ErrDuplicateEmail()
			}
			return errors.ErrInvalidInput("Duplicate user data")
		}
		return errors.ErrDatabase(err)
	}

	// Update user ID with inserted ID if it was generated by MongoDB
	if oid, ok := result.InsertedID.(primitive.ObjectID); ok {
		user.ID = oid.Hex()
	}

	return nil
}

// FindByID finds a user by ID
func (r *userRepository) FindByID(ctx context.Context, id string) (*models.User, error) {
	log := mlog.L(ctx)
	startTime := time.Now()
	var user models.User

	// Try to parse as ObjectID first, if fails use as string
	var filter bson.M
	if oid, err := primitive.ObjectIDFromHex(id); err == nil {
		filter = bson.M{"_id": oid}
	} else {
		filter = bson.M{"_id": id}
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find user by ID"), filter)
	//

	err := r.collection.FindOne(ctx, filter).Decode(&user)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by ID"), map[string]any{
			"error": err.Error(),
		})
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	maskingData := []logger.MaskRule{{
		Field: "result.email",
		Type:  logger.MaskEmail,
	}, {
		Field:  "result.username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	}}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by ID"), map[string]any{
		"result": user,
	}, maskingData...)

	return &user, nil
}

// FindByUsername finds a user by username
func (r *userRepository) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	log := mlog.L(ctx)
	startTime := time.Now()
	var user models.User

	filter := bson.M{"username": username}

	//
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find user by username"), filter, logger.MaskRule{
		Field:  "username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	})
	//
	err := r.collection.FindOne(ctx, filter).Decode(&user)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by username"), map[string]any{
			"error": err.Error(),
		})
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}
	maskingData := []logger.MaskRule{{
		Field: "result.email",
		Type:  logger.MaskEmail,
	}, {
		Field:  "result.username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	}}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   "users",
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by username"), map[string]any{
		"result": user,
	}, maskingData...)

	return &user, nil
}

// FindByEmail finds a user by email
func (r *userRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	log := mlog.L(ctx)
	startTime := time.Now()

	var user models.User

	filter := bson.M{"email": email}

	//
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Find user by email"), filter, logger.MaskRule{
		Field: "email",
		Type:  logger.MaskEmail,
	})
	//
	err := r.collection.FindOne(ctx, filter).Decode(&user)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by email"), map[string]any{
			"error": err.Error(),
		})
		if err == mongo.ErrNoDocuments {
			return nil, errors.ErrUserNotFound()
		}
		return nil, errors.ErrDatabase(err)
	}

	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Find user by email"), map[string]any{
		"result": user,
	}, logger.MaskRule{
		Field: "result.email",
		Type:  logger.MaskEmail,
	}, logger.MaskRule{
		Field:  "result.username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	})

	return &user, nil
}

// containsField checks if error message contains a field name
func containsField(errMsg, field string) bool {
	// Simple check if field name appears in error message
	for i := 0; i < len(errMsg)-len(field)+1; i++ {
		if errMsg[i:i+len(field)] == field {
			return true
		}
	}
	return false
}

// SearchByUsername searches users by username prefix
func (r *userRepository) SearchByUsername(ctx context.Context, query string, limit int) ([]*models.User, error) {
	log := mlog.L(ctx)
	startTime := time.Now()

	if limit <= 0 {
		limit = 10
	}

	// Use regex for prefix search (case-insensitive)
	filter := bson.M{
		"username": bson.M{
			"$regex":   "^" + query,
			"$options": "i",
		},
	}

	// Log the DB request
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency: r.collection.Name(),
	}).Debug(logAction.DB_REQUEST(logAction.DB_READ, "Search users by username"), filter, logger.MaskRule{
		Field:  "username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	})
	//

	cursor, err := r.collection.Find(ctx, filter)
	end := time.Since(startTime).Microseconds()
	if err != nil {
		log.SetDependencyMetadata(logger.DependencyMetadata{
			Dependency:   r.collection.Name(),
			ResponseTime: end,
		}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Search users by username"), map[string]any{
			"error": err.Error(),
		})
		return nil, errors.ErrDatabase(err)
	}
	defer cursor.Close(ctx)

	var users []*models.User
	count := 0
	for cursor.Next(ctx) && count < limit {
		var user models.User
		if err := cursor.Decode(&user); err != nil {
			continue
		}
		users = append(users, &user)
		count++
	}

	maskingData := []logger.MaskRule{{
		Field: "result.email",
		Type:  logger.MaskEmail,
	}, {
		Field:  "result.username",
		Type:   logger.MaskPartial,
		Prefix: 2,
	}}
	log.SetDependencyMetadata(logger.DependencyMetadata{
		Dependency:   r.collection.Name(),
		ResponseTime: end,
	}).Debug(logAction.DB_RESPONSE(logAction.DB_READ, "Search users by username"), map[string]any{
		"result_count": len(users),
		"result":       users,
	}, maskingData...)

	return users, nil
}
